create table if not exists importance
(
    importance_id   bigint generated by default as identity
        constraint importance_pk
            primary key,
    importance_name varchar(255) not null
);

alter table importance
    owner to postgres;

create table if not exists recipe_book
(
    recipe_id    bigint generated by default as identity
        constraint recipe_book_pk
            primary key,
    recipe_name  varchar(255) not null,
    products_xml varchar(255) not null,
    steps_xml    varchar(255) not null
);

alter table recipe_book
    owner to postgres;

create table if not exists repetitions_type
(
    repetition_type_id bigint generated by default as identity
        constraint repetitions_type_pk
            primary key,
    repetition_type    varchar(255) not null
);

alter table repetitions_type
    owner to postgres;

create table if not exists role
(
    role_id   bigint generated by default as identity
        constraint role_pk
            primary key,
    role_type varchar(255)
);

alter table role
    owner to postgres;

create table if not exists units_measurement
(
    units_measurement_id         bigint generated by default as identity
        constraint units_measurement_pk
            primary key,
    units_measurement_name       varchar(255) not null,
    units_measurement_short_name varchar(255) not null
);

alter table units_measurement
    owner to postgres;

create table if not exists shopping_cart
(
    product_id           bigint generated by default as identity
        constraint shopping_cart_pk
            primary key,
    product_name         varchar(255) not null,
    product_quantity     varchar(255) not null,
    units_measurement_id bigint  not null
        constraint shopping_cart_units_measurement_units_measurement_id_fk
            references units_measurement
);

alter table shopping_cart
    owner to postgres;

create table if not exists type_case
(
    type_case_id   bigint generated by default as identity
        constraint type_case_pk
            primary key,
    importance_id  bigint not null
        constraint type_case_importance_importance_id_fk
            references importance,
    type_case_name varchar(255)
);

alter table type_case
    owner to postgres;

create table if not exists "user"
(
    user_id   bigint generated by default as identity
        constraint user_pk
            primary key,
    role_id   bigint  not null
        constraint user_role_role_id_fk
            references role,
    user_name varchar(255) not null
);

alter table "user"
    owner to postgres;

create table if not exists tasks
(
    task_id            bigint generated by default as identity
        constraint tasks_pk
            primary key,
    type_case_id       bigint    not null
        constraint tasks_type_case_type_case_id_fk
            references type_case,
    executor_user_id   bigint    not null
        constraint tasks_user_user_id_fk
            references "user",
    subject_user_id    bigint
        constraint tasks_user_user_id_fk2
            references "user",
    name_task          varchar(255)   not null,
    event_date         timestamp not null,
    creator_user_id    bigint    not null
        constraint tasks_user_user_id_fk3
            references "user",
    create_date        date      not null,
    description        varchar(255),
    repetition_type_id bigint    not null
        constraint tasks_repetitions_type_id_fk
            references repetitions_type
);

alter table tasks
    owner to postgres;